USE ROLE SAMBA_ADMIN;
--Create a Warehouse dedicated to Samba ------
CREATE OR REPLACE WAREHOUSE SAMBA_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- Database and schemas
CREATE OR REPLACE DATABASE SAMBA_DB;
USE DATABASE SAMBA_DB;

CREATE OR REPLACE SCHEMA RAW_STAGE;
CREATE OR REPLACE SCHEMA TRANSFORMED;
CREATE OR REPLACE SCHEMA PRODUCTION;