USE ROLE SAMBA_DATA_ENGINEER;
Use SAMBA_DB;
CREATE OR REPLACE FILE FORMAT RAW_STAGE.samba_json_format
  TYPE = 'JSON'
  STRIP_OUTER_ARRAY = TRUE;
  --IGNORE_NULL_VALUES = TRUE;


  CREATE OR REPLACE FILE FORMAT RAW_STAGE.samba_csv_format
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('\\N','NULL','')
  EMPTY_FIELD_AS_NULL = TRUE
  TRIM_SPACE = TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;


 