--moving the transformed data into PRODCUTION schema ready ready for OLAP
USE ROLE SYSADMIN;
CREATE OR REPLACE TABLE PRODUCTION.DIM_DATE   CLONE TRANSFORMED.DIM_DATE;
CREATE OR REPLACE TABLE PRODUCTION.DIM_PRODUCT CLONE TRANSFORMED.DIM_PRODUCT;
CREATE OR REPLACE TABLE PRODUCTION.DIM_CITY    CLONE TRANSFORMED.DIM_CITY;
CREATE OR REPLACE TABLE PRODUCTION.DIM_BRANCH  CLONE TRANSFORMED.DIM_BRANCH;
CREATE OR REPLACE TABLE PRODUCTION.DIM_STAFF   CLONE TRANSFORMED.DIM_STAFF;